name: Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: herlbeng/prueba-actions-linter/.github/workflows/pylint.yml@main
      with:
      config-path: .github/workflows/pylint.yml
