name: Actions

on: [push]
  workflow_dispatch:

jobs:
  Pylint:
    uses: herlbeng/prueba-actions-linter/.github/workflows/pylint.yml@main
    with:
      config-path: .github/workflows/pylint.yml
  Upload:      
    uses: herlbeng/prueba-actions-linter/.github/workflows/s3.yml@main
    with:
      config-path: .github/workflows/s3.yml               