name: Actions

on: [push]

jobs:
  Pylint:
    uses: herlbeng/prueba-actions-linter/.github/workflows/pylint.yml@main
  Upload:      
    uses: herlbeng/prueba-actions-linter/.github/workflows/s3.yml@main